version: 2
updates:
  # npm依存関係の更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      # 開発依存関係をグループ化してPR数を削減
      development-dependencies:
        patterns:
          - "@biomejs/*"
          - "@vitest/*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actionsの更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci/cd"
